MxOnline/urls.py
#_*_ encoding:utf-8 _*_

"""MxOnline URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
import xadmin
from django.views.static import serve
from users.views import LoginView, RegisterView, ActiveUserView, ForgetPwdView, ResetView, ModifyPwdView, LogoutView
from users.views import IndexView
from organization.views import OrgView
from MxOnline.settings import MEDIA_ROOT

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url('^$', IndexView.as_view(), name="index"), #process static file
    url('^login/$', LoginView.as_view(), name="login"),
    url('^logout/$', LogoutView.as_view(), name="logout"),
    url('^register/$', RegisterView.as_view(), name="register"),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name="user_active"),
    url(r'^forget/$', ForgetPwdView.as_view(), name="forget_pwd"),
    url(r'^reset/(?P<active_code>.*)/$', ResetView.as_view(), name="reset_pwd"),
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name="modify_pwd"),
    #organization url setting
    url(r'^org/', include('organization.urls', namespace="org")),
    #the process function that configure the upload file's access
    url(r'^media/(?P<path>.*)', serve, {"document_root":MEDIA_ROOT}),

    # Production mode
    # url(r'^static/(?P<path>.*)', serve, {"document_root": STATIC_ROOT}),
    # courses relative url setting
    url(r'^course/', include('courses.urls', namespace="course")),
    # teacher relative url setting
    url(r'^teacher/', include('courses.urls', namespace="teacher")),
    # user relative url setting
    url(r'^users/', include('users.urls', namespace="users")),
    #contact us app url
    url(r'^contact/', include('contactus.urls')),

    #ueditor related url
    url(r'^ueditor/',include('DjangoUeditor.urls' )),
    url(r'^cart_payment/',include('cart_payment.urls', namespace="cart_payment" )),
    url(r'^aboutus', TemplateView.as_view(template_name='about_us.html'),name='aboutus'),
    url(r'^howitworks', TemplateView.as_view(template_name='how_it_works.html'),name='howitworks'),
    url(r'^terms', TemplateView.as_view(template_name='terms_service.html'),name='terms'),
    url(r'^privacy', TemplateView.as_view(template_name='privacy_policy.html'),name='privacy')

]
#404 page set up
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'
# urlpatterns += staticfiles_urlpatterns()

apps/organization/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'Yujia Lian'
__date__ = '6/21/17 9:50 AM'

from django.conf.urls import url, include
from .views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView
from .views import AddFavView, TeacherListView, TeacherDetailView
urlpatterns = [
    #course organization list
    url(r'^list/$', OrgView.as_view(), name="org_list"),
    url(r'^add_ask/$', AddUserAskView.as_view(), name="add_ask"),
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name="org_home"),
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name="org_course"),
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name="org_desc"),
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name="org_teacher"),

    #collection
    url(r'^add_fav/$', AddFavView.as_view(), name="add_fav"),

    #Teacher list page
    url(r'^teacher/list/$', TeacherListView.as_view(), name="teacher_list"),

    #teacher detail page
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name="teacher_detail")
]

apps/users/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'Yujia Lian'
__date__ = '7/4/17 1:22 AM'

from django.conf.urls import url, include
from .views import UserinfoView, UploadImageView, UpdatePwdView, SendEmailCodeView, UpdateEmailView, mylesson
from .views import MyCourseView, MyFavOrgView, MyFavTeacherView, MyFavCourseTView, MyMessageView
from .views import become_instructor, become_instructor_markup_data, become_instructor_api_view,try_for_free

urlpatterns = [
    #User detail page
    url(r'^info/$', UserinfoView.as_view(), name="user_info"),

    #User head upload
    url(r'^image/upload/$', UploadImageView.as_view(), name= 'image_upload'),

    #user center change password
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name='update'),

    #send email verify code
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name='sendemail_code'),

    # modify email
    url(r'^update_email/$', UpdateEmailView.as_view(), name='update_email'),

    #My courses
    url(r'^mycourse/$', MyCourseView.as_view(), name='mycourse'),

    #Add Course
    url(r'^addcourse/$', become_instructor, name='addcourse'),

    #My lesson
    url(r'^mylesson/$', mylesson, name='mylesson'),

    # My course collection
    url(r'^myfav/org/$', MyFavOrgView.as_view(), name='myfav_org'),

    # My teacher collection
    url(r'^myfav/teacher/$', MyFavTeacherView.as_view(), name='myfav_teacher'),

    # My course collection
    url(r'^myfav/course/$', MyFavCourseTView.as_view(), name='myfav_course'),

    # My message
    url(r'^mymessage/$', MyMessageView.as_view(), name='mymessage'),

    # Become a Instructor
    url(r'^become_instructor/$', become_instructor, name='become_instructor'),

    # Become a Instructor markup data
    url(r'^become_instructor_markup_data/$', become_instructor_markup_data, name='become_instructor_markup_data'),

    # Become a Instructor api view
    url(r'^become_instructor_api_view/$', become_instructor_api_view, name='become_instructor_api_view'),

    url(r'^try_for_free/$', try_for_free, name='try_for_free')


]

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/contact_success.html
{% extends "base.html" %}

{% block title %}Contact Us Success{% endblock %}

{% block css %}
<style>
  p {
    font-size: 1.15em;
  }
</style>
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-12  col-md-12 col-sm-12">
		<h2 class="title">Thanks!</h2>

		<p>
			We appreciate your feedback.<br /> Someone from the team will be in
			touch with you shortly.
		</p>

		

		</div>
	</div>
</div>
{% endblock %}

templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block custom_title %}Organization-Main Page{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block custom_js %}{% endblock %}
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">

            {% if request.user.is_authenticated %}
                <div class="top">
				    <div class="wp">
					    <div class="fl"><p>Contact：<b>3042169199</b></p></div>
					    <!--登录后跳转-->
                            {% if request.user.is_authenticated %}
                            <div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
	                                <dd>
	                                    <h2>{{ request.user.nick_name }}</h2>
	                                    <p>{{ request.user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url 'users:user_info' %}">Go to user center</a>
	                                <a class="fr" href="{% url 'logout' %}">Logout</a>
                                </div>
                            </div>
                        </div>
                            <a href="{% url 'users:mymessage' %}">
                                <div class="msg-num"><span id="MsgNum">{{ request.user.unread_nums }}</span></div>
                            </a>
                        {% else %}
                            <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">Register</a>
                            <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">Login</a>
                        {% endif %}


				    </div>
			    </div>
            {% else %}
                <div class="top">
				<div class="wp">
					<div class="fl"><p>Contact：<b>3042169199</b></p></div>
					<!--登录后跳转-->
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">Register</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">Login</a>
				</div>
			</div>
            {% endif %}

        <div class="middle companyheader">
            <div class="wp">
                <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                <div class="head fl">
                    <h1>
                        Infyni Higher education
                        <img src="{% static 'images/authentication.png' %}"/>
                        <img src="{% static 'images/gold.png' %}"/>
                    </h1>
                    <p class="fl">
                        <span class="fl" style="margin-top:8px;color:#848484;">Hot index: </span>
                        <span class="precision company-credit" data-star-scope="5.0"></span>
                        <span class="key">{{ course_org.fav_nums }}</span>
                    </p>
                </div>
                <div class="btn fr collectionbtn  notlogin
                     "data-favid="22" data-fav-type="1">
                     {% if has_fav %}Added{% else %}Collection{% endif %}
                </div>
            </div>
        </div>
    </div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index' %}">Main</a>></li>
			<li><a href="{% url "org:org_list" %}">Organization</a>></li>
			<li>{% block page_title_path %}Organization Details{% endblock %}</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% ifequal current_page 'home' %}active2{% endifequal %}"><a href="{% url 'org:org_home' course_org.id %}">Organization</a></li>
                <li class="{% ifequal current_page 'course' %}active2{% endifequal %}"><a href="{% url 'org:org_course' course_org.id %}">Courses</a></li>
                <li class="{% ifequal current_page 'desc' %}active2{% endifequal %}"><a href="{% url 'org:org_desc' course_org.id %}">Description</a></li>
                <li class="{% ifequal current_page 'teacher' %}active2{% endifequal %}"><a href="{% url 'org:org_teacher' course_org.id %}">Teacher</a></li>
			</ul>
		</div>

{% block right_form %}
{% endblock %}
    </div>
</section>

<!--sidebar end-->
<!--header start-->
{#</div>#}
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url "org:add_fav" %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == 'Please login first!'){
                    window.location.href="/login/";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this), {{ course_org.id }}, 2);
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path : "{% static 'images' %}",
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['Worst', 'bad', 'Average', 'Good', 'Excellent'],
                    noRatedMsg  : 'No comments yet.',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function() {
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , 'Collection');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>

templates/payment.html
<html>
<p>Redirecting to Paytm</p>
<form method="post" action={{paytm_url}} name="f1">
<table border="1">
<tbody>
{% for key,value in paytmdict.items %}
    <input type="hidden" name="{{key}}" value="{{value}}">
{% endfor %}
</tbody>
</table>
<script type="text/javascript">
document.f1.submit();
</script>
</form>
</html>

templates/usercenter-fav-org.html
{% extends 'usercenter-base.html' %}
{% block title %}My collection-{{block.super}}{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
    <section class="breadCrumbC">
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">Main</a>></li>
                <li><a href="{% url 'users:user_info' %}">User center</a>></li>
                <li>My Classes</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right" >
            <div class="tab_headerCont">
                    <ul class="tab_header clearfix">
                        <li class="active"><a href=" "> My Classes</a></li> 
                    </ul>
                </div>



            <!-- <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'users:myfav_org' %}">Organization</a> </li>
                        <li><a href="{% url 'users:myfav_teacher' %}">Teacher </a></li>
                        <li><a href="{% url 'users:myfav_course' %}">Courses</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for org in org_list %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:org_home' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:org_home' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}"/>


                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}
                </div>
            </div> -->
        </div>
{% endblock %}
</body>
</html>

templates/usercenter-message.html
{% extends 'usercenter-base.html' %}
{% block title %}My messages-{{block.super}}{% endblock %}

{% block custom_bread %}
    <section class="breadCrumbC">
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">Main</a>></li>
                <li><a href="{% url 'users:user_info' %}">User center</a>></li>
                <li>My messages</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right" >
	 
		<div class="personal_des permessage">
                <div class="tab_headerCont">
                        <ul class="tab_header clearfix">
                            <li class="active"><a href=" "> My Messages</a></li> 
                        </ul>
                    </div>
			<div class="messagelist">
                    {% for message in messages.object_list %}
                    <div class="messages">
                        <div class="fr">
                            <div class="top"><span class="fl time">{{ message.add_time }}</span><span class="fr btn foldbtn"></span></div>
                            <p>
                                {{ message.message }}
                            </p>
                        </div>
                    </div>
                    {% endfor %}


			</div>


			<div class="pageturn pagerright">
                <ul class="pagelist">
                    {% if messages.has_previous %}
                        <li class="long"><a href="?{{ messages.previous_page_number.querystring }}">Previous page</a></li>
                    {% endif %}
                    {% for page in messages.pages %}
                        {% if page %}
                            {% ifequal page messages.number %}
                                <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                            {% else %}
                                <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                            {% endifequal %}
                        {% else %}
                            <li class="none"><a href="">...</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if messages.has_next %}
                        <li class="long"><a href="?{{ messages.next_page_number.querystring }}">Next page</a></li>
                    {% endif %}
            </ul>
            </div>
		</div>

	</div>
{% endblock %}
</body>
</html>